import { DefaultTheme } from 'styled-components';

const theme: DefaultTheme = {
  colors: {
    primary: '#4a5568',
    secondary: '#2d3748',
    background: '#f7fafc',
    text: '#2d3748',
    buttonText: '#fff',
    border: '#e2e8f0',
    overlay: 'rgba(0, 0, 0, 0.8)',
  },
  fonts: {
    main: 'Arial, sans-serif',
  },
  fontSizes: {
    heading: '2.5rem',
    subheading: '1.5rem',
    body: '1rem',
  },
  spacing: {
    small: '0.5rem',
    medium: '1rem',
    large: '2rem',
  },
  borderRadius: '8px',
  boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  components: {
    toggleContainer: {
      display: 'inline-flex',
      backgroundColor: '#f0f0f0',
      padding: '4px',
      borderRadius: '8px',
      gap: '4px',
    },
    toggleButton: {
      padding: '8px 16px',
      border: 'none',
      borderRadius: '6px',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      fontSize: '14px',
      fontWeight: 500,
      height: '40px',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    activeButton: {
      backgroundColor: '#fff',
      boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
      color: '#000',
    },
    inactiveButton: {
      backgroundColor: 'transparent',
      color: '#666',
    },
    heading: {
      fontSize: '2.5rem',
      fontWeight: '600',
      color: '#2d3748',
      marginBottom: '1.5rem',
      borderBottom: '3px solid #e2e8f0',
      paddingBottom: '0.5rem',
      background: 'linear-gradient(to right, #2d3748, #4a5568)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      letterSpacing: '-0.025em',
    },
    controlsContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '1.5rem',
      marginBottom: '2rem',
    },
    selectorContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
    },
    label: {
      fontSize: '14px',
      fontWeight: '500',
      color: '#2d3748',
    },
    select: {
      padding: '8px 12px',
      borderRadius: '6px',
      border: '1px solid #e2e8f0',
      backgroundColor: '#fff',
      fontSize: '14px',
      color: '#2d3748',
      cursor: 'pointer',
      outline: 'none',
      transition: 'all 0.2s ease',
      height: '40px',
      '&:hover': {
        borderColor: '#cbd5e0',
      },
      '&:focus': {
        borderColor: '#4a5568',
        boxShadow: '0 0 0 3px rgba(74, 85, 104, 0.1)',
      },
    },
    actionButton: {
      backgroundColor: '#4a5568',
      color: '#fff',
      padding: '10px 20px',
      borderRadius: '8px',
      border: 'none',
      fontSize: '16px',
      fontWeight: '500',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
      height: '40px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
      '&:hover': {
        backgroundColor: '#2d3748',
        transform: 'translateY(-1px)',
        boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
      },
      '&:disabled': {
        backgroundColor: '#cbd5e0',
        cursor: 'not-allowed',
        transform: 'none',
      },
    },
  },
};

export default theme; 